import { vi } from 'vitest';

export function clientWith(
  price: { price: number; currency: string } | undefined,
  isPremium = false,
) {
  return {
    checkDomain: vi.fn().mockResolvedValue({
      results: [
        {
          domain: 'x.com',
          status: 'free',
          is_premium: isPremium,
          price: price ? { product: price } : undefined,
        },
      ],
    }),
    listDomains: vi.fn(),
    getDomain: vi.fn(),
    listContacts: vi.fn(),
    getContact: vi.fn(),
    registerDomain: vi.fn(),
    updateDomain: vi.fn(),
    createContact: vi.fn(),
    updateContact: vi.fn(),
    deleteContact: vi.fn(),
    suggestDomain: vi.fn(),
    getDomainAuthcode: vi.fn(),
    resetDomainAuthcode: vi.fn(),
    approveDomainTransfer: vi.fn(),
    sendFoa1DomainTransfer: vi.fn(),
    deleteDomain: vi.fn(),
    restartDomainOperation: vi.fn(),
    renewDomain: vi.fn(),
    transferDomain: vi.fn(),
    tradeDomain: vi.fn(),
    restoreDomain: vi.fn(),
    listDnsZones: vi.fn(),
    getDnsZone: vi.fn(),
    listDnsZoneRecords: vi.fn(),
    listNameservers: vi.fn(),
    getNameserver: vi.fn(),
    listNsGroups: vi.fn(),
    getNsGroup: vi.fn(),
    listDnsTemplates: vi.fn(),
    getDnsTemplate: vi.fn(),
    createDnsZone: vi.fn(),
    updateDnsZone: vi.fn(),
    createNameserver: vi.fn(),
    updateNameserver: vi.fn(),
    createNsGroup: vi.fn(),
    updateNsGroup: vi.fn(),
    createDnsTemplate: vi.fn(),
    createDomainToken: vi.fn(),
    deleteDnsZone: vi.fn(),
    deleteNameserver: vi.fn(),
    deleteNsGroup: vi.fn(),
    deleteDnsTemplate: vi.fn(),
    listTlds: vi.fn(),
    getTld: vi.fn(),
    getDomainPrice: vi.fn(),
    listTags: vi.fn(),
    createTag: vi.fn(),
    deleteTag: vi.fn(),
    listSslProducts: vi.fn(),
    getSslProduct: vi.fn(),
    listSslOrders: vi.fn(),
    getSslOrder: vi.fn(),
    getSslApproverEmails: vi.fn(),
    createSslOrder: vi.fn(),
    renewSslOrder: vi.fn(),
    reissueSslOrder: vi.fn(),
    cancelSslOrder: vi.fn(),
    updateSslOrder: vi.fn(),
    updateSslApproverEmail: vi.fn(),
    resendSslApproverEmail: vi.fn(),
    createCsr: vi.fn(),
    decodeCsr: vi.fn(),
    createSslOtpToken: vi.fn(),
    listCustomers: vi.fn(),
    getCustomer: vi.fn(),
    createCustomer: vi.fn(),
    updateCustomer: vi.fn(),
    deleteCustomer: vi.fn(),
    listEmailTemplates: vi.fn(),
    createEmailTemplate: vi.fn(),
    updateEmailTemplate: vi.fn(),
    deleteEmailTemplate: vi.fn(),
    listEmailVerificationDomains: vi.fn(),
    startEmailVerification: vi.fn(),
    restartEmailVerification: vi.fn(),
    getDmarc: vi.fn(),
    listDmarcSubscriptions: vi.fn(),
    createDmarc: vi.fn(),
    retryDmarc: vi.fn(),
    dmarcSsoLogin: vi.fn(),
    deleteDmarc: vi.fn(),
    getSpamExpertsDomain: vi.fn(),
    spamExpertsLoginUrl: vi.fn(),
    createSpamExpertsDomain: vi.fn(),
    updateSpamExpertsDomain: vi.fn(),
    deleteSpamExpertsDomain: vi.fn(),
    listLicensePrices: vi.fn(),
    listLicenseItems: vi.fn(),
    listPleskLicenses: vi.fn(),
    getPleskLicense: vi.fn(),
    getPleskKey: vi.fn(),
    createPleskLicense: vi.fn(),
    updatePleskLicense: vi.fn(),
    resetPleskHwid: vi.fn(),
    deletePleskLicense: vi.fn(),
  };
}
